version: "3"
networks:
  app-tier:
    driver: bridge
services:
  asciidoctor:
    tty: true
    stdin_open: true
    container_name: asciidoctor
    build:
      context: .
      dockerfile: Dockerfile
    image: asciidoctor.live
    command: "bash src/provisioning/startup/asciidoctor/startup.sh"
    volumes:
      - ./:/var/www/docker
    networks:
      - app-tier
  guard:
    tty: true
    stdin_open: true
    container_name: guard
    image: asciidoctor.live
    command: "bash src/provisioning/startup/guard/startup.sh"
    volumes:
      - ./:/var/www/docker
    networks:
      - app-tier
  browser-sync:
    tty: true
    stdin_open: true
    container_name: browser-sync
    image: asciidoctor.live
    command: "bash src/provisioning/startup/browser-sync/startup.sh"
    volumes:
      - ./:/var/www/docker
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - app-tier